# numpy
* numpy stands for numerical python and is the core library for numeric and scientific learning.
* it consists of multi dimensional array objects and a collection of routines for collecting those arrays. 

# single dimensional numpy array


In [1]:
import numpy as np
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [2]:
type(n1)

numpy.ndarray

# multi dimensional array

In [3]:
n2 = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,9]])
n2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 9]])

In [4]:
type(n2)

numpy.ndarray

# numpy array with only zeros

In [5]:
n3 = np.zeros(1)
n3


array([0.])

In [6]:
n3 = np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
n3 = np.zeros((6,6))
n3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# initializing numpy with same numbers

In [8]:
n4 = np.full((3,3),10)
n4

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [9]:
n4 = np.full((6,6),10)
n4

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

# initializing numpy array within a range

In [10]:
n5 = np.arange(10,50)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
n5 = np.arange(10,50,19)
n5

array([10, 29, 48])

# initializing numpy array with random numbers

In [13]:
import random
n6 = np.random.randint(1,45,3)
n6

array([27,  4,  9])

In [14]:
n6 = np.random.randint(1,45,3)
n6

array([14, 23, 37])

# checking the shape of a numpy array

In [15]:
n7 = np.array([[1,2,3],[4,5,6]])
n7

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.shape(n7)

(2, 3)

In [17]:
n7.shape

(2, 3)

In [20]:
n7.shape = (3,2)
n7

array([[1, 2],
       [3, 4],
       [5, 6]])

# *** STACKING FUNCTIONS IN NUMPY ***
* 1) vstack()
* 2) hstack()
* 3) column_stack()

# vstack()
* vertically stack the arrays on the top of each other

In [21]:
import numpy as np
n8 = np.array([1,2,3,4])
n9 = np.array([4,5,6,7])
np.vstack((n8,n9))

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

# hstack()
* horizontally stack the arrays on the top of each other

In [26]:
import numpy as np
n8 = np.array([1,2,3,4])
n9 = np.array([4,5,6,7])
np.hstack((n8,n9))

array([1, 2, 3, 4, 4, 5, 6, 7])

# column_stack()
* columnwise stack the arrays on the top of each other

In [28]:
import numpy as np
n8 = np.array([1,2,3,4])
n9 = np.array([4,5,6,7])
np.column_stack((n8,n9))

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

#  *@  *NumPy intersection and difference*  @
* intersect1d(n1,n2) - common elements present in both the arrays
* setdiff1d(n1,n2) - elements present in n1 but not in n2
* setdiff1d(n2,n1) - elements present in n2 but not in n1


In [29]:
n10 = np.array([1,2,3,4])
n11 = np.array([3,4,7,9])

In [30]:
np.intersect1d(n10,n11)

array([3, 4])

In [32]:
np.setdiff1d(n10,n11)

array([1, 2])

In [33]:
np.setdiff1d(n11,n11)

array([], dtype=int32)

In [34]:
np.setdiff1d(n11,n10)

array([7, 9])

* ADDITION OF NUMPY ARRAYS

In [37]:
n12 = np.array([2,3,4,5])
n13 = np.array([5,6,7,8])
np.sum((n12,n13))

40

In [38]:
np.sum([n12,n13],axis = 1)

array([14, 26])

In [39]:
np.sum([n12,n13],axis = 0)

array([ 7,  9, 11, 13])

* basic math

In [41]:
n12 +1


array([3, 4, 5, 6])

In [42]:
n12 * 33

array([ 66,  99, 132, 165])

In [43]:
n12 -5 

array([-3, -2, -1,  0])

In [44]:
n12 / 5

array([0.4, 0.6, 0.8, 1. ])

In [45]:
np.min(n12)

2

In [46]:
np.mean(n12)

3.5

In [47]:
np.median(n12)

3.5

In [48]:
np.std(n12)

1.118033988749895

# Save and Load a Numpy array 

In [49]:
n13 = np.array([3,4,5,6,7])
np.save('my_numpy_array',n13)

In [50]:
np.load('my_numpy_array.npy')

array([3, 4, 5, 6, 7])

#     Intro to pandas

In [55]:
import pandas as pd
df = pd.Series([1,2,3,4,5,6,77])

df

0     1
1     2
2     3
3     4
4     5
5     6
6    77
dtype: int64

In [61]:
pd.DataFrame(df,columns=['Rudra'])

Rudra
0      1
1      2
2      3
3      4
4      5
5      6
6     77

In [59]:
pd.DataFrame(df)

0
0   1
1   2
2   3
3   4
4   5
5   6
6  77

In [65]:
df1 = pd.Series([1,2,3,4,5,6,77],index=['a','e','i ','o','u','m','n'])

In [63]:
df1


a      1
e      2
i      3
o      4
u      5
m      6
n     77
dtype: int64

In [66]:
df2 = pd.Series({'a': 100,'b': 200,'c':300})
df2

a    100
b    200
c    300
dtype: int64

In [67]:
df3 = pd.Series({'a': 100,'b': 200,'c':300},index=['c','e','v','b','a'])
df3

c    300.0
e      NaN
v      NaN
b    200.0
a    100.0
dtype: float64

In [68]:
df2['a']

100

In [69]:
df3['v']

nan

In [70]:
df4 = pd.Series([1,2,3,4,5,6,77])

In [71]:
df4

0     1
1     2
2     3
3     4
4     5
5     6
6    77
dtype: int64

In [74]:
df4[3]

4

In [75]:
df4[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [76]:
df4[-3:]

4     5
5     6
6    77
dtype: int64

# * basic arithmatic operation

In [77]:
df4 +24

0     25
1     26
2     27
3     28
4     29
5     30
6    101
dtype: int64

In [78]:
df4 -6

0    -5
1    -4
2    -3
3    -2
4    -1
5     0
6    71
dtype: int64

In [79]:
df4 * 50

0      50
1     100
2     150
3     200
4     250
5     300
6    3850
dtype: int64

In [80]:
df4/6

0     0.166667
1     0.333333
2     0.500000
3     0.666667
4     0.833333
5     1.000000
6    12.833333
dtype: float64

In [81]:
import math
df4.pow(3)

0         1
1         8
2        27
3        64
4       125
5       216
6    456533
dtype: int64

In [84]:
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([3,4,5])
s1,s2

(0    1
 1    2
 2    3
 3    4
 dtype: int64,
 0    3
 1    4
 2    5
 dtype: int64)

In [85]:
s1 + s2

0    4.0
1    6.0
2    8.0
3    NaN
dtype: float64

In [86]:
s1 - s2

0   -2.0
1   -2.0
2   -2.0
3    NaN
dtype: float64

In [87]:
s1*s2

0     3.0
1     8.0
2    15.0
3     NaN
dtype: float64

In [88]:
s1/s2

0    0.333333
1    0.500000
2    0.600000
3         NaN
dtype: float64

# DataFrame in Pandas

In [89]:
pd.DataFrame({'rudra':[1,2,3,4,5],'satya':[6,7,8,9,10]})

rudra  satya
0      1      6
1      2      7
2      3      8
3      4      9
4      5     10

In [90]:
df4= pd.DataFrame({'Name':['ROOH','NOT_AVAILABLE','ITS_ME','SNEHA'],'Marks':[6,7,8,9]})

In [91]:
df4

Name  Marks
0           ROOH      6
1  NOT_AVAILABLE      7
2         ITS_ME      8
3          SNEHA      9

In [99]:
df5 =pd.read_csv('friends.csv')

In [100]:
df5.tail()

Unnamed: 0   name  marks          city
0           0  harry     12       cuttack
1           1  rudra     34         banki
2           2  satya     24      keonjhar
3           3  subha     67  bhubaneshwar

In [102]:
df5.shape

(4, 4)

In [104]:
df5.describe()

Unnamed: 0      marks
count    4.000000   4.000000
mean     1.500000  34.250000
std      1.290994  23.613203
min      0.000000  12.000000
25%      0.750000  21.000000
50%      1.500000  29.000000
75%      2.250000  42.250000
max      3.000000  67.000000

In [105]:
df5.iloc[1:3,1:3]

name  marks
1  rudra     34
2  satya     24