# PYTHON NUMPY TUTORIAL

# Numpy provides efficient storage
#it also provides better ways of handling data for processing
#it is fast
#it is easy to learn
#NumPy uses relatively less memory to store data

In [6]:
import numpy as np

In [7]:
myarr = np.array([3,6,32,7])

In [8]:
myarr

array([ 3,  6, 32,  7])

In [9]:
myarr = np.array([3,6,32,7],np.int32)
myarr

array([ 3,  6, 32,  7])

In [10]:
myarrr[0,1]

NameError: name 'myarrr' is not defined

In [11]:
myarr = np.array([[3,6,32,7]],np.int64)

In [12]:
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [13]:
myarr[0,1]

6

In [14]:
myarr.shape

(1, 4)

In [15]:
myarr.dtype

dtype('int64')

In [16]:
myarr[0,1]=45

In [17]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

#there are generally five ways to create array
1. conversion from other python structures(ex-list,tuple)
2.intrinsic numpy array creation objects(arange,ones,zeros.....)
3.reading arrays from disk,either from standard or custom formats.
4.creating arrays from raw bytes through the useof strings or buffers.
5.use of special library functions(ex.random)

#Array creation :conversion from other python structures(ex-list,tuple)

In [18]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [19]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [20]:
listarray.dtype

dtype('int32')

In [21]:
listarray.shape

(3, 3)

In [22]:
listarray.size

9

In [23]:
np.array({1,2,3,4})

array({1, 2, 3, 4}, dtype=object)

In [24]:
np.array({1,2,3,3})# as it produces OBJECT TYPE array and object type array is not efficient for us sometime

array({1, 2, 3}, dtype=object)

In [25]:
zeros = np.zeros((2,5))

#intrinsic numpy array creation objects(arange,ones,zeros.....)

In [26]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
rng = np.arange(15)# give array from 0 to 14
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
lspace = np.linspace(1,5,12)# gives equallly spaced 12 elements from 1 to 5
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [29]:
llspace = np.linspace(1,50,10)
llspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [30]:
ll1space=np.linspace(1,10)
ll1space

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [31]:
len(ll1space)

50

In [32]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [33]:
ide = np.identity(45)# it gives us identity matrix
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [34]:
ide.shape

(45, 45)

In [35]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr = arr.reshape(3,33)# it will reshape the given array into prospective shape given by the user
#but the given reshepe should be multiplier of the elemt like here  3*33 = 99 

# arr

In [37]:
arr = arr.ravel() #IT WILL CONVERT THE MULTIDIRECTIONAL ARRAY TO ONE DIRECTIONAL ARRAY

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# 1d array - 1axis
# 2d array- axis 0, axis 1
 #in numpy axis start from axis 0
 
 |
 |  axis 0(vertically downward)
 
 _ _ axis 1(horizintally from left to right)

In [39]:
x = [[1,2,3],[4,5,6],[7,8,9]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [40]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
ar.sum(axis = 0)

array([12, 15, 18])

In [42]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [43]:
ar.T #TRANSPOSE

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
ar.flat # it gives A ITERATOR

In [48]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [49]:
ar.ndim# it shos NUMBER OF DIMENSION

2

In [50]:
ar.size

9

In [51]:
ar.nbytes#total number of bytes consumed by hole array

36

In [52]:
one = np.array([1,3,4,634,2])
one

array([  1,   3,   4, 634,   2])

In [53]:
one.argmax()# it is in the format of atribute thats why ( ) used


3

In [54]:
one.argmin()

0

In [55]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int32)

# argmin() - it give the indx position of smallest element in the array
# argmax()- it gives the index position of largest element in the array
# argsort()- it ives the indices of the array in a way by which if we arrange the elements of the array it should be in a ascending order.

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
ar.argmin()

0

In [58]:
ar.argmax()

8

In [59]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int32)

In [60]:
ar.argmax(axis = 0)

array([2, 2, 2], dtype=int32)

In [61]:
ar.argmin(axis = 1)

array([0, 0, 0], dtype=int32)

In [62]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int32)

In [63]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [64]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
ar2 = np.array([[1,4,6],[3,5,4],[7,8,6]])
ar2

array([[1, 4, 6],
       [3, 5, 4],
       [7, 8, 6]])

In [69]:
ar + ar2

array([[ 2,  6,  9],
       [ 7, 10, 10],
       [14, 16, 15]])

In [70]:
ar * ar2

array([[ 1,  8, 18],
       [12, 25, 24],
       [49, 64, 54]])

In [71]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [72]:
ar.sum()

45

In [73]:
ar.min()

1

In [74]:
ar.max()

9

In [75]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int32), array([2, 0, 1, 2], dtype=int32))

In [77]:
np.count_nonzero(ar)

9

In [78]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int32))

In [79]:
ar[1,2] = 0
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

In [80]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int32))

# nonzero() - it gives index position of the nonzero element of the array
# count_nonzero() - it gives total number of nonzero elements of the arrary

In [81]:
import sys

In [82]:
py_ar = [0,4,55,2]

In [83]:
np_ar =np.array(py_ar)

In [84]:
np_ar

array([ 0,  4, 55,  2])

In [86]:
sys.getsizeof(1)* len(py_ar)

56

In [87]:
np_ar.itemsize * np_ar.size

16

# here NumPy uses very less memory than system